ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'ACCOUNTS';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'INVOICE_UPDATE';
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
